name: 'Codex Aura Analyze'
description: 'Analyze codebase and generate dependency graph'
branding:
  icon: 'git-branch'
  color: 'purple'

inputs:
  path:
    description: 'Path to analyze'
    required: false
    default: '.'
  edge-types:
    description: 'Edge types to extract'
    required: false
    default: 'imports,calls,extends'
  output:
    description: 'Output file path'
    required: false
    default: 'codex-aura-graph.json'
  comment-on-pr:
    description: 'Add comment to PR with results'
    required: false
    default: 'false'

outputs:
  graph-file:
    description: 'Path to generated graph file'
  node-count:
    description: 'Number of nodes in graph'
  edge-count:
    description: 'Number of edges in graph'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.edge-types }}
    - ${{ inputs.output }}
    - ${{ inputs.comment-on-pr }}